name: 24h Auto Update to FC2

on:
  schedule:
    - cron: '0 */6 * * *' # 6時間おきに実行
  workflow_dispatch: # 手動実行ボタンも追加

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: pip install requests

    - name: Run update script
      run: python update_site.py

    - name: Deploy to FC2 via FTP
      uses: SamKirkland/FTP-Deploy-Action@4.3.0
      with:
        server: ${{ secrets.FC2_FTP_SERVER }}
        username: ${{ secrets.FC2_FTP_USER }}
        password: ${{ secrets.FC2_FTP_PASSWORD }}
        local-dir: ./


    - name: Deploy to FC2 via FTP
      uses: SamKirkland/FTP-Deploy-Action@4.3.0
      with:
        server: ftp.fc2.com
        username: mikivaluejapan
        password: ${{ secrets.FC2_FTP_PASSWORD }}
        local-dir: ./
        port: 21
        protocol: ftp

